spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/file-uplaod
    username: postgres
    password: ramzi
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
server:
  port: 9090